spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soa?characterEncoding=utf8&useSSL=true
    password: soa
    username: soa
    driver-class-name: com.mysql.jdbc.Driver
  application:
      name: pay-provider
  jpa:
    properties:
      hibernate:
        show-sql: true
        format-sql: true

eureka:
  client:
    serviceUrl:
      # 服务中心地址
      defaultZone: http://localhost:8000/eureka/

server:
  port: 8400
logging:
  level:
    org:
      hibernate:
        SQL: debug

