spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soa?characterEncoding=utf8&useSSL=true
    password: soa
    username: soa
    driver-class-name: com.mysql.jdbc.Driver
  application:
      name: pay-authority-provider

eureka:
  client:
    serviceUrl:
      # ָ服务中心地址
      defaultZone: http://localhost:8000/eureka/

server:
  port: 8200
